"""Jubran's menu, as printed on its morning, evening, drinks, desserts and shisha menus.

Each category is (name_ar, name_en, dishes) and each dish is
(name_ar, name_en, description_ar, description_en, price in JOD). Dishes that the
printed menus price as "ask your server" (soup of the day, dish of the day, the
seasonal fruit platter) and the set menus for groups of 16+ are not table orders,
so they are left out. Paid additions printed next to a dish ("add chicken +2.45")
are dishes of the Extras category, so they can be ordered as their own line.
"""

MENU = (
    ("الفطور", "Breakfast", (
        ("فول", "Foul (Fava Beans)", "فول مدمس على الطريقة الشامية. نباتي بالكامل.", "Levantine-style fava beans. Vegan.", "4.50"),
        ("فلافل", "Falafel", "أقراص فلافل مقرمشة. نباتي بالكامل.", "Crispy falafel. Vegan.", "3.50"),
        ("مشاط زهرة", "Cauliflower Mshat", "زهرة مقلية مقرمشة.", "Crispy fried cauliflower.", "3.50"),
        ("لبنة مع خضروات", "Labaneh & Veggies", "لبنة مع خضار طازجة. نباتي. من توصيات الشيف.", "Labaneh with fresh vegetables. Vegetarian. Chef's recommendation.", "4.50"),
        ("لبنة بلدية", "Labaneh Baladyeh", "لبنة بلدية بزيت الزيتون. نباتي.", "Local labaneh with olive oil. Vegetarian.", "3.00"),
        ("سجق وبيض", "Sujjuk & Eggs", "من الفرن: سجق وبيض على العجينة.", "From the oven: sujjuk and eggs on dough.", "6.50"),
        ("تيركي وجبنة", "Turkey & Cheese", "من الفرن: تيركي وجبنة على العجينة.", "From the oven: turkey and cheese on dough.", "6.00"),
        ("شكشوكة", "Shakshouka", "بيض مطبوخ بصلصة البندورة والفلفل.", "Eggs cooked in a tomato and pepper sauce.", "6.50"),
        ("إفطار كونتينينتال", "Continental Breakfast", "بيض على طريقتك، سجق، سبانخ، فطر سوتيه، بيف بيكن، بندورة كرزية وفاصولياء مطبوخة. من توصيات الشيف.", "Eggs your way, sujjuk, spinach, mushrooms sauté, beef bacon, cherry tomatoes and baked beans. Chef's recommendation.", "11.00"),
        ("بيض على طريقتك", "Eggs Your Way", "بينيديكت، مخفوق، بوشيه، أومليت، مسلوق أو عيون. ممكن إضافة سالمون مدخن.", "Benedict, scrambled, poached, omelette, boiled or sunny side up. Smoked salmon can be added (the Smoked Salmon side).", "6.50"),
        ("بيض سبيناتشي باريميجيانو", "Spinaci Parmigiano Eggs", "خبز بريوش مع بيض مخفوق وسبانخ وبارميزان. من توصيات الشيف. ممكن إضافة سالمون مدخن.", "Brioche bread topped with scrambled eggs, spinach and parmesan. Chef's recommendation. Smoked salmon can be added (the Smoked Salmon side).", "8.00"),
        ("هاش براونز", "Potato Hash Browns", "أقراص بطاطا مقرمشة. من توصيات الشيف.", "Crispy potato hash browns. Chef's recommendation.", "3.75"),
        ("مارميليدز وعسل", "Marmalades & Honey", "تشكيلة مربيات وعسل وزبدة.", "Assortment of marmalades, honey and butter.", "4.75"),
        ("سالمون أو أفوكادو توست", "On Toast (Salmon or Avocado)", "توست مع أفوكادو وبندورة شوكولاتة، أو سالمون مدخن مع كريم تشيز حسب اختيارك. من توصيات الشيف.", "Toast topped with your choice of avocado and chocolate tomatoes, or smoked salmon with cream cheese. Chef's recommendation.", "9.75"),
        ("كرواسان", "Croissant", "كرواسان بالزبدة. يحتاج وقت تحضير أطول.", "Butter croissant. Needs extra preparation time.", "5.50"),
        ("سالمون مدخن", "Smoked Salmon", "سالمون نرويجي مدخن، طبق جانبي.", "Norwegian smoked salmon, as a side.", "4.00"),
        ("بيف بيكن", "Beef Bacon", "بيكن لحم بقري، طبق جانبي.", "Beef bacon, as a side.", "3.00"),
        ("سلطة فواكه", "Fruit Salad", "فواكه طازجة مقطعة.", "Fresh cut fruit.", "7.50"),
        ("جرانولا وزبادي", "Granola & Yoghurt", "جرانولا مع زبادي بالفراولة أو التوت الأزرق أو الباشن فروت. من توصيات الشيف.", "Granola with yoghurt and strawberry, blueberry or passion fruit. Chef's recommendation.", "7.00"),
        ("فرينش توست", "French Toast", "توست فرنسي محلى. من توصيات الشيف.", "Sweet French toast. Chef's recommendation.", "5.00"),
        ("وافل", "Waffle", "وافل طازج.", "Freshly made waffle.", "7.00"),
        ("بان كيك", "Pancake", "بان كيك طازج.", "Freshly made pancakes.", "6.50"),
    )),
    ("المقبلات الباردة", "Cold Appetizers", (
        ("حمص", "Hummus", "حمص بالطحينة وزيت الزيتون. نباتي بالكامل. ممكن إضافة لحمة أو صنوبر.", "Hummus with tahini and olive oil. Vegan. Meat or pine nuts can be added.", "4.20"),
        ("حمص بالجوز والريحان", "Basil Walnut Hummus", "حمص بالريحان والجوز وزيت الزيتون. نباتي بالكامل. من توصيات الشيف.", "Hummus with basil, walnuts and olive oil. Vegan. Chef's recommendation.", "5.00"),
        ("حمص بيروتي", "Hummus Beiruti", "حمص بليمون وبقدونس زيادة، مع صنوبر وزيت زيتون. نباتي بالكامل. من توصيات الشيف.", "Hummus with extra lemon and parsley, topped with pine nuts and drizzled with olive oil. Vegan. Chef's recommendation.", "5.85"),
        ("متبل شمندر بالجوز", "Muttabal Beetroot", "شمندر مقطع مع طحينة وليمون، مع جوز على الوجه. نباتي.", "Diced beetroot mixed with tahini and lemon, topped with walnuts. Vegetarian.", "5.00"),
        ("متبل باذنجان مشوي", "Muttabal Eggplant", "باذنجان مشوي على الفحم مع ليمون وطحينة، ورمان وزيت زيتون على الوجه. نباتي.", "Chargrilled eggplants with lemon and tahini, topped with pomegranates and olive oil. Vegetarian.", "4.65"),
        ("بابا غنوج", "Baba Ghanouj", "باذنجان مشوي مع خضار. نباتي بالكامل.", "Grilled eggplant with vegetables. Vegan.", "4.70"),
        ("محمرة بالجوز", "Muhammara", "مكسرات مطحونة مع فلفل حلو وبندورة وبصل وبقسماط، مع زيت زيتون. نباتي بالكامل.", "Mixed nuts blended with sweet peppers, tomatoes, onions and bread crumbs, drizzled with olive oil. Vegan.", "4.95"),
        ("شنكليش", "Shanklish", "تشكيلة أجبان مع بصل وبندورة مفرومة، متبلة بالزعتر وزيت الزيتون. نباتي.", "A selection of mixed cheeses with finely chopped onions and tomatoes, seasoned with oregano and olive oil. Vegetarian.", "6.00"),
        ("فتة", "Fatteh", "على اختيارك (باذنجان مقلي وحمص) أو (أرز ودجاج وسمن)، مع خبز مقرمش ولبن ولوز. من توصيات الشيف.", "Your choice of (fried eggplant and chickpeas) or (rice, chicken and ghee), with crispy bread, topped with yoghurt and almonds. Chef's recommendation.", "6.80"),
        ("يلنجي ورق عنب وكوسا", "Yalanji", "ورق عنب وكوسا محشي أرز وحشوة نباتية، على لبن مع دبس رمان. نباتي.", "Cooked vine leaves and zucchini stuffed with rice and a vegetarian filling, on a bed of yoghurt, drizzled with pomegranate molasses. Vegetarian.", "6.45"),
        ("كبة نية", "Kibbeh Neyyeh", "لحم بقري نيء طازج مع برغل ودبس وصنوبر، مع بصل وأيولي وفجل وزيت زيتون. من توصيات الشيف.", "Fresh raw beef blended with bulgur, pekmez and pine nuts, served with onions, aioli, radish and olive oil. Chef's recommendation.", "9.65"),
        ("حراق أصبعه", "Huraq Osbao", "عدس مع عجينة خاصة، مع خبز مقرمش وتمر هندي وبصل مقرمش وثوم وكزبرة، ودبس رمان وأعشاب. نباتي بالكامل. من توصيات الشيف.", "Lentils and special dough topped with crunchy bread, tamarind, crispy onions and garlic coriander, drizzled with pomegranate molasses and herbs. Vegan. Chef's recommendation.", "4.70"),
    )),
    ("السلطات", "Salads", (
        ("سلطة كيل وكينوا", "Kale & Quinoa Salad", "كينوا وكيل طازج مع بندورة كرزية ورمان وأفوكادو وبرتقال وجبنة فيتا، وصلصة دبس الرمان والبرتقال. نباتي. من توصيات الشيف.", "Fresh quinoa and kale with cherry tomatoes, pomegranates, avocado, orange slices, feta cheese and a pomegranate molasses orange dressing. Vegetarian. Chef's recommendation.", "8.25"),
        ("سلطة الندى", "Dew Goddess Salad", "خس وجرجير وكوسا وأفوكادو وخيار وبندورة كرزية وبرتقال وبارميزان، مع صلصة الريحان. نباتي. ممكن إضافة دجاج.", "Lettuce, rocca, zucchinis, avocado chunks, cucumbers, cherry tomatoes, orange slices and parmesan with basil vinaigrette. Vegetarian. Chicken can be added.", "8.85"),
        ("سلطة بوراتا", "Burrata Salad", "بندورة ملونة وأوراق فجل وثوم معمر وأوراق صغيرة مع جبنة بوراتا، وصلصة البلسميك والبيستو. نباتي.", "Black, yellow and red heirloom tomatoes, radish leaves, chives, baby leaves and burrata cheese with balsamic pesto vinaigrette. Vegetarian.", "11.50"),
        ("سلطة مانجو ديلايت", "Mango Delight Salad", "خس آيسبرغ وفراولة وأفوكادو وتمر ومانجو وزيتون أسود وجوز وسمسم أسود وبارميزان، مع صلصة الخردل والعسل. نباتي. من توصيات الشيف.", "Iceberg lettuce, strawberries, avocado, dates, mango, black olives, walnuts, black sesame seeds and parmesan with a mustard honey vinaigrette. Vegetarian. Chef's recommendation.", "11.00"),
        ("سلطة قارب الأناناس", "Caribbean Boat Salad", "نصف أناناس محشي جرجير ومكعبات أناناس وعسل وفراولة وجوز وفواكه مجففة، مع صلصة البلسميك وزيت الزيتون والعسل. نباتي بالكامل.", "Half a pineapple stuffed with rocca, pineapple cubes, honey, strawberries, walnuts and dried fruits, with a balsamic olive oil and honey dressing. Vegan.", "11.50"),
        ("سلطة سيزر", "Caesar Crunch Salad", "سلطة سيزر مقرمشة. ممكن إضافة دجاج.", "Crunchy Caesar salad. Chicken can be added.", "6.40"),
        ("سلطة حلوم بالريحان", "Halloumi Pesto Salad", "جبنة حلوم على خس وجرجير وكزبرة وبقدونس وزعتر بري ونعنع وفلفل حلو وخيار وبندورة وزيتون أخضر مشوي، مع صلصة البيستو. نباتي. من توصيات الشيف. ممكن إضافة دجاج.", "Halloumi cheese on iceberg lettuce, arugula, coriander, parsley, wild thyme, mint, sweet green peppers, cucumbers, heirloom tomatoes and grilled green olives with basil pesto vinaigrette. Vegetarian. Chef's recommendation. Chicken can be added.", "7.80"),
        ("سلطة كيل وفريكة", "Kale & Freekeh Salad", "فلفل ملون وخيار وكيل وبندورة كرزية وجبنة فيتا وتمر ورمان وشمندر، مع صلصة العسل. نباتي.", "Green, yellow and red peppers, cucumber, kale, cherry tomatoes, feta cheese, dates, pomegranates and beetroot with honey vinaigrette. Vegetarian.", "8.85"),
        ("سلطة عدس وسبانخ", "Lentil Spinaci Salad", "عدس وسبانخ وبصل أحمر ورمان وأفوكادو وبندورة كرزية ونعنع وسماق وليمون، مع مايونيز ودبس رمان. نباتي.", "Lentils, spinach, red onions, pomegranates, avocado chunks, cherry tomatoes, mint, sumac and lemon with mayo and pomegranate molasses vinaigrette. Vegetarian.", "7.70"),
        ("سلطة جرجير وشمندر", "Beetroot & Arugula Salad", "جرجير وشمندر وبصل وبندورة كرزية وسماق، مع جوز وجبنة فيتا وصلصة دبس الرمان. نباتي.", "Arugula and beetroot with onions, cherry tomatoes and sumac, topped with walnuts and feta cheese in a pomegranate molasses vinaigrette. Vegetarian.", "7.20"),
        ("سلطة سبانخ وشمندر", "Beetroot Spinaci Salad", "سبانخ وبصل أحمر وبندورة كرزية وشمندر وجريب فروت وبرتقال وبيكان وجوز وبذور دوار الشمس وسماق، مع جبنة فيتا وصلصة القيقب والتوت البري. نباتي. من توصيات الشيف.", "Spinach, red onions, cherry tomatoes, beetroot, grapefruit, orange wedges, pecans, walnuts, sunflower seeds and sumac, topped with feta cheese and a maple cranberry vinaigrette. Vegetarian. Chef's recommendation.", "8.85"),
        ("فتوش", "Fattoush", "سلطة الفتوش مع خبز مقرمش. نباتي بالكامل.", "Fattoush salad with crispy bread. Vegan.", "5.95"),
        ("تبولة شمندر", "Beetroot Tabbouleh", "تبولة بالشمندر. نباتي بالكامل.", "Tabbouleh with beetroot. Vegan.", "5.60"),
    )),
    ("المقبلات الساخنة", "Hot Appetizers", (
        ("حمص باللحم", "Hummus Bel Lahem", "حمص مع مكعبات فيليه تندرلوين وصنوبر.", "Hummus with fillet tenderloin cubes and pine nuts.", "7.00"),
        ("سجق أرمني", "Sujuk Armani", "سجق مفروم مشوي على الفحم مع صنوبر، مدخن بالصلصة الأرمنية الخاصة.", "Minced sausages chargrilled, topped with pine nuts and smoked with an Armenian special sauce.", "6.85"),
        ("كبدة الدجاج بدبس الرمان", "Molasses Chicken Liver", "كبدة دجاج مقلية مع ثوم ودبس رمان وزيت زيتون.", "Pan sautéed chicken liver and garlic with pomegranate molasses and olive oil.", "6.65"),
        ("بطاطا حرة بالكزبرة", "Spicy Potato & Coriander", "مكعبات بطاطا مقلية مع كزبرة وثوم وفلفل مدخن حار وزيت زيتون. نباتي.", "Cubes of potatoes fried with coriander, garlic, spiced smoked pepper and virgin olive oil. Vegetarian.", "5.60"),
        ("مسخن بلادي", "Musakhan Bladi", "خبز طابون مع دجاج مسحب وبصل مكرمل بالسماق، مع صنوبر وزيت زيتون. من توصيات الشيف.", "Layered taboon bread topped with pulled chicken and caramelized onions with sumac, pine nuts and olive oil. Chef's recommendation.", "9.95"),
        ("حلوم", "Halloumi", "جبنة حلوم على اختيارك: مشوي بالريحان أو حلوم هاش. نباتي.", "Halloumi cheese, your choice of grilled with pesto or hash halloumi. Vegetarian.", "6.60"),
        ("كبة حماتي", "Stuffed Kebbeh", "كبة بيتية محشية لحمة مفرومة وبصل وصنوبر. السعر للحبة الواحدة. من توصيات الشيف.", "Homemade croquettes stuffed with minced meat, onions and pine nuts. Priced per piece. Chef's recommendation.", "2.45"),
        ("سمبوسك جبنة", "Cheese Sambosic", "عجينة ملفوفة باليد محشية جبنة بالزعتر، مقلية لحد ما تقرمش. نباتي.", "Hand-rolled pastry stuffed with zaatar and cheese, fried to a golden crisp. Vegetarian.", "4.60"),
        ("أرانشيني دي ريزو", "Arancini di Riso", "كرات ريزوتو مقلية بنكهة الكمأة مع فطر بورتوبيلو وبارميزان. نباتي. من توصيات الشيف.", "Crispy fried risotto balls with truffle, portobello mushrooms and parmesan. Vegetarian. Chef's recommendation.", "9.20"),
        ("فريكة بالفطر والكريمة", "Creamy Mushroom Freekeh", "فريكة مدخنة مطبوخة بكريمة الألفريدو والفطر والبارميزان. نباتي. ممكن إضافة دجاج.", "Smoked cracked wheat cooked with alfredo cream, mushrooms and parmesan. Vegetarian. Chicken can be added.", "6.95"),
        ("دايناميت جمبري أو دجاج", "Dynamite Shrimp or Chicken", "جمبري أو دجاج تمبورا مقرمش بصلصة الدايناميت الحارة، على اختيارك. حار.", "Crispy shrimp or chicken tempura (your choice) tossed with our spicy dynamite sauce. Spicy.", "9.25"),
    )),
    ("الصاجيات", "Potteries", (
        ("صاجية جبران", "Jubran's Special", "مكعبات تندرلوين مطبوخة مع البصل والخوخ والتين المجفف والفلفل الأحمر والفطر.", "Beef tenderloin cubes cooked in an onion stew with dried plums and figs, red peppers and mushrooms.", "13.00"),
        ("قلاية بندورة باللحمة", "Galayet Bandoura", "مقلاة بندورة طازجة مع لحمة وأعشاب شرقية وصنوبر، مع خبز للتغميس.", "Traditional pan of fresh cooked tomatoes, meat, middle eastern herbs and pine nuts, served with pita bread for dipping.", "9.50"),
        ("صاجية لحمة", "Traditional Lamb Sajiyeh", "مكعبات فيليه تندرلوين مقلية مع بصل، مع صنوبر ولوز. من توصيات الشيف.", "Stir-fried diced fillet tenderloin and onions topped with pine nuts and almonds. Chef's recommendation.", "14.50"),
    )),
    ("الشوربات", "Soups", (
        ("شوربة ثمار البحر", "Seafood Soup", "شوربة ثمار البحر مع جمبري وبلح بحر أسود، مزينة بأوراق الفجل والثوم المعمر.", "Seafood soup with shrimp and black mussels, garnished with radish leaves and chives.", "9.50"),
        ("شوربة خضار", "Hearty Vegetable Soup", "شوربة خضار. نباتي بالكامل. ممكن إضافة دجاج.", "Vegetable soup. Vegan. Chicken can be added.", "4.45"),
        ("شوربة بروكلي", "Broccoli Soup", "شوربة بروكلي. نباتي.", "Broccoli soup. Vegetarian.", "5.60"),
        ("شوربة الفطر بالكريمة", "Creamy Mushroom Soup", "شوربة فطر بالكريمة. نباتي.", "Creamy mushroom soup. Vegetarian.", "6.80"),
    )),
    ("الباستا والريزوتو", "Pasta & Risotto", (
        ("سباغيتي سبيناتشي", "Spaghetti Spinaci", "سباغيتي بالسبانخ بصلصة السبانخ والكريمة مع بارميزان وأوراق سبانخ صغيرة. نباتي. من توصيات الشيف. ممكن إضافة دجاج.", "Spinach spaghetti in a creamy spinach sauce with parmesan and baby spinach leaves. Vegetarian. Chef's recommendation. Chicken can be added.", "8.25"),
        ("فتوشيني ألفريدو", "Fettuccine Alfredo", "فتوشيني بصلصة الألفريدو والفطر وشرائح البارميزان. نباتي. ممكن إضافة دجاج.", "Fettuccine with rich alfredo cream sauce, mushrooms and parmesan shavings. Vegetarian. Chicken can be added.", "8.00"),
        ("ريجاتوني أرابياتا أو روزيه", "Rigatoni Arrabbiata or Rosé", "ريجاتوني مع زيتون وبارميزان، بصلصة الأرابياتا الحارة أو الروزيه حسب اختيارك. نباتي. ممكن إضافة دجاج.", "Rigatoni with olives and parmesan shavings in your choice of spicy arrabbiata or rosé sauce. Vegetarian. Chicken can be added.", "8.25"),
        ("لازانيا الفورنو", "Lasagne al Forno", "لازانيا لحم بقري بالبندورة والبشاميل بالفرن. يحتاج وقت تحضير أطول.", "Oven-baked beef lasagna with tomato and béchamel. Needs extra preparation time.", "11.00"),
        ("فتوشيني تارتوفو", "Fettuccine al Tartufo", "فتوشيني بصلصة الفطر والكمأة مع شرائح البارميزان. نباتي. من توصيات الشيف. ممكن إضافة دجاج.", "Fettuccine with a truffle-infused mushroom sauce and parmesan shavings. Vegetarian. Chef's recommendation. Chicken can be added.", "11.50"),
        ("لينجويني ثمار البحر", "Linguine ai Frutti di Mare", "لينجويني مع جمبري تايجر وسالمون وفيليه سمك.", "Linguine with tiger shrimp, salmon and tender fish fillet.", "12.00"),
        ("بورتوبيلو ريزوتو", "Portobello Infused Risotto", "أرز أربوريو كريمي بفطر البورتوبيلو مع بارميزان مبشور. نباتي. من توصيات الشيف. ممكن إضافة دجاج.", "Creamy arborio rice with portobello mushrooms, topped with grated parmesan. Vegetarian. Chef's recommendation. Chicken can be added.", "12.25"),
        ("صيادية ريزوتو", "Risotto Sayadiyeh", "ريزوتو بالزعفران مطبوخ بمرق السمك، مع سمكة اليوم وبصل مكرمل وصنوبر. من توصيات الشيف.", "Creamy saffron risotto cooked in fish stock, topped with seared catch of the day, caramelized onions and pine nuts. Chef's recommendation.", "13.60"),
    )),
    ("من الفرن", "From The Oven", (
        ("صفيحة أرمنية", "Armenian Safeeha", "عجينة مع لحم خروف مفروم وبهارات أرمنية ودبس رمان، مع جرجير وصنوبر وليمون. ممكن إضافة زيت الكمأة.", "Minced lamb pastry with Armenian mixed spices and pomegranate molasses, topped with rocca, pine nuts and lemon slices. Truffle oil can be added.", "8.00"),
        ("سبانخ وجبنة فيتا", "Spinaci & Feta Cheese", "عجينة من الفرن مع سبانخ وجبنة فيتا. من توصيات الشيف. ممكن إضافة زيت الكمأة.", "Oven-baked dough with spinach and feta cheese. Chef's recommendation. Truffle oil can be added.", "9.25"),
        ("مناقيش", "Manaqish", "مناقيش من الفرن، اسأل عن الأنواع المتوفرة. نباتي. ممكن إضافة زيت الكمأة.", "Oven-baked manaqish; ask about today's toppings. Vegetarian. Truffle oil can be added.", "5.25"),
        ("بيتزا مارجاريتا", "Margherita Pizza", "صلصة البندورة والريحان مع جرجير صغير وموزاريلا فيور دي لاتيه. نباتي. ممكن إضافة زيت الكمأة.", "Tomato basil sauce, baby arugula and fior di latte fresh mozzarella. Vegetarian. Truffle oil can be added.", "8.00"),
        ("بيتزا بيبروني", "Pepperoni Pizza", "بيبروني وصلصة البندورة والريحان مع جرجير صغير وموزاريلا فيور دي لاتيه. ممكن إضافة زيت الكمأة.", "Pepperoni, tomato basil sauce, baby arugula and fior di latte fresh mozzarella. Truffle oil can be added.", "9.25"),
        ("بيتزا الخضار", "Vegetarian Pizza", "صلصة البندورة والريحان مع باذنجان وكوسا وفلفل وفطر وزيتون أسود وبصل وجرجير وموزاريلا وكريم تشيز. نباتي. ممكن إضافة زيت الكمأة.", "Tomato basil sauce, eggplants, zucchinis, peppers, fresh mushrooms, black olives, onions, baby arugula, fior di latte mozzarella and cream cheese. Vegetarian. Truffle oil can be added.", "9.25"),
        ("بيتزا تارتوفو", "Pizza al Tartufo", "بيتزا بالكمأة مع فطر بورتوبيلو وريحان وموزاريلا فيور دي لاتيه. نباتي. من توصيات الشيف. ممكن إضافة زيت الكمأة.", "Truffle-infused pizza with portobello mushrooms, basil and fior di latte fresh mozzarella. Vegetarian. Chef's recommendation. Truffle oil can be added.", "11.00"),
        ("بيتزا أربع أجبان", "Quattro Formaggi Pizza", "موزاريلا فيور دي لاتيه وإيمنتال وبارميزان وجبنة زرقاء مع زعتر، على صلصة البندورة والريحان. نباتي. من توصيات الشيف. ممكن إضافة زيت الكمأة.", "Fior di latte mozzarella, emmental, parmesan and blue cheese with oregano on our tomato basil sauce. Vegetarian. Chef's recommendation. Truffle oil can be added.", "9.25"),
        ("بيتزا باربيكيو الدجاج", "BBQ Chicken Pizza", "صلصة ترياكي وبصل أحمر وفطر المحار ودجاج طري. ممكن إضافة زيت الكمأة.", "Tangy teriyaki sauce, red onions, oyster mushrooms and tender chicken. Truffle oil can be added.", "9.25"),
    )),
    ("البرغر والساندويشات", "Burgers & Sandwiches", (
        ("سموكستاك انجوس", "Smokestack Angus", "لحم أنجوس مدخن مسحب مطبوخ ببطء بصلصة الباربيكيو وجبنة شيدر، في خبز بريوش. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Shredded smoked angus beef slow cooked with our house barbecue sauce and cheddar cheese in a grilled brioche bun. Served with curved potatoes and garden salad.", "14.50"),
        ("جورميه برغر", "Gourmet Burger", "قطعتين لحم واغيو مع صلصة الفطر والكمأة وجبنة إيمنتال. من توصيات الشيف. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Two smashed Wagyu beef patties with creamy mushroom truffle sauce and melted emmental cheese. Chef's recommendation. Served with curved potatoes and garden salad.", "15.50"),
        ("جمبري رول", "Shrimp Roll", "خبز بريوش محمص مليان جمبري مع خضار مفرومة بصلصة المايونيز الخاصة. من توصيات الشيف. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Toasted brioche bun full of tender shrimp and chopped veggies in our house mayo sauce. Chef's recommendation. Served with curved potatoes and garden salad.", "11.50"),
        ("نشمي برغر", "Nashmi Burger", "قطعة لحم واغيو (150 غم) مشوية على الحجر مع بصل مشوي وبندورة وجبنة ومخلل، وصلصة جبران. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Stone grilled Wagyu beef patty (150 g) with grilled onions, tomatoes, cheese and pickles and Jubran's sauce. Served with curved potatoes and garden salad.", "11.45"),
        ("كريسبي تشيكن برغر", "Crispy Chicken Burger", "خبز بريوش مع خس وصدر دجاج مقرمش، بصلصة الدايناميت أو العسل والخردل حسب اختيارك. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Brioche bun, lettuce and crispy chicken breast in your choice of dynamite or honey mustard sauce. Served with curved potatoes and garden salad.", "10.45"),
        ("رويال تشيكن برغر", "Royal Chicken Burger", "صدر دجاج مقرمش بالبانكو الياباني مع خس ومخلل وجبنة وصلصة مايونيز خاصة في خبز بريوش. يقدم مع بطاطا كيرفد وسلطة خضراء.", "Crispy chicken breast in a Japanese panko crust with lettuce, pickles, cheese and special mayo sauce in a brioche bun. Served with curved potatoes and garden salad.", "9.95"),
    )),
    ("الأطباق الجانبية", "Side Orders", (
        ("بطاطا", "Potatoes", "مهروسة، أو مقلية على اختيارك: فرنسية، كيرفد، ودجز أو حلوة.", "Mashed, or fried your way: French, curved, wedges or sweet.", "4.25"),
        ("أرز ولبن", "Rice & Yoghurt", "أرز مع لبن.", "Rice with yoghurt.", "3.85"),
        ("أرز الياسمين", "Jasmine Rice", "أرز الياسمين.", "Jasmine rice.", "2.40"),
        ("خبز الجبنة بالثوم", "Cheesy Garlic Bread", "خبز بالثوم والجبنة.", "Garlic bread with cheese.", "4.85"),
        ("لبن وخيار بالنعنع", "Cucumber & Yoghurt with Mint", "لبن مع خيار ونعنع.", "Yoghurt with cucumber and mint.", "3.70"),
        ("خضار سوتيه", "Sautéed Vegetables", "خضار مشكلة سوتيه.", "Sautéed mixed vegetables.", "5.95"),
        ("خضار طازجة", "Vegetables Crudités", "خضار طازجة مقطعة.", "Fresh cut vegetables.", "4.25"),
        ("كبيس مخلل", "Kabis Pickles", "مخلل بيتي وزيتون.", "Homemade pickles and olives.", "3.90"),
    )),
    ("الأطباق الرئيسية", "Main Course", (
        ("ستيك بيف تندرلوين", "Beef Tenderloin Steak", "ستيك تندرلوين (250 غم) على الحجر الساخن مع خضار سوتيه وصلصة الفطر أو الفلفل وبطاطا كيرفد. يقدم على طبق ساخن.", "Beef tenderloin steak (250 g) on hot stone with sautéed vegetables, mushroom or pepper sauce and curved potatoes. Served on a sizzling plate.", "28.00"),
        ("ستيك رب آي", "Rib-Eye Steak Frites", "ستيك رب آي (350 غم) على الحجر الساخن مع خضار سوتيه وصلصة الفطر أو الفلفل وبطاطا كيرفد. يقدم على طبق ساخن.", "Rib-eye steak (350 g) on hot stone with sautéed vegetables, mushroom or pepper sauce and curved potatoes. Served on a sizzling plate.", "39.00"),
        ("سالمون فيليه", "Seared Salmon Fillet", "فيليه سالمون بصلصة الترياكي على سبانخ طازجة وكرنب بروكسل وهليون وجزر ملون. من توصيات الشيف. يحتاج وقت تحضير أطول.", "Teriyaki-glazed salmon on fresh spinach leaves, brussels sprouts, asparagus and rainbow carrots. Chef's recommendation. Needs extra preparation time.", "26.00"),
        ("جمبري تايجر", "Tiger Shrimp", "جمبري تايجر بصلصة الترياكي مع سلطة أفوكادو وبندورة كرزية وبرغل إيتش أرمني. من توصيات الشيف. يحتاج وقت تحضير أطول.", "Tiger shrimp in teriyaki sauce with an avocado cherry tomato salad and Armenian eetch bulgur. Chef's recommendation. Needs extra preparation time.", "34.60"),
        ("بايلا ڤالنسيانا (لشخصين)", "Paella Valenciana (for two)", "أرز أربوريو مع لوبستر وسلطعون وجمبري وكاليماري وفيليه سمك وسالمون وبلح بحر وجزر وبصل. يكفي شخصين. يحتاج وقت تحضير أطول.", "Arborio rice with lobster, crab, shrimps, calamari, fish fillets, salmon fillets, mussels, carrots and onions. Serves two. Needs extra preparation time.", "32.00"),
        ("سيخ شاورما دجاج", "Chicken Shawarma Skewer", "سيخ شاورما دجاج (300 غم) بالبهارات الخاصة مع بندورة وبصل ومخلل وخبز تورتيلا وصلصة أيولي.", "Chicken shawarma skewer (300 g) with our special spices, served with tomatoes, onions, pickles, tortilla bread and aioli sauce.", "14.75"),
        ("سيخ شاورما لحمة", "Beef Shawarma Skewer", "سيخ شاورما لحم أنجوس (300 غم) بالبهارات الخاصة مع بندورة وبصل ومخلل وخبز تورتيلا وطحينة.", "Angus beef shawarma skewer (300 g) with our special spices, served with tomatoes, onions, pickles, tortilla bread and tahini.", "17.00"),
        ("صدر دجاج لبناني", "Lebanese Chicken Breast", "صدر دجاج مشوي على الفحم بصلصة الزبدة والليمون أو البيستو بالكريمة أو الفطر الأبيض حسب اختيارك، مع خضار سوتيه وبطاطا كيرفد.", "Chargrilled chicken breast with your choice of butter lemon, creamy pesto or white mushroom sauce, served with sautéed vegetables and curved potatoes.", "16.50"),
        ("رقبة مدخنة", "Smoked Lamb Neck", "رقبة خروف مدخنة ومطبوخة ببطء، متبلة بخلطة البهارات الخاصة، مع أطباق جانبية. طبق جبران المميز. من توصيات الشيف. يحتاج وقت تحضير أطول.", "Our signature smoked slow-cooked lamb neck, marinated in a house blend of aromatic spices, with sides. Chef's recommendation. Needs extra preparation time.", "37.00"),
    )),
    ("من المشوى", "From The Grill", (
        ("كباب خشخاش", "Kebab Khashkhash", "كباب على الطريقة الحلبية بصلصة الخشخاش، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن. حار. ممكن إضافة فستق.", "Aleppo style kebab skewers with khashkhash sauce, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate. Spicy. Pistachios can be added.", "13.50"),
        ("دجاج جبران على الفحم", "Jubran Grilled Chicken", "دجاج متبل بخلطة جبران الخاصة، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Chicken marinated with Jubran's signature spices, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "12.50"),
        ("عرايس", "Arayes", "لحمة مفرومة مع بندورة وبصل، مشوية في خبز بيتي، مع لبن.", "Minced meat with diced tomatoes and onions, grilled in homemade pita bread, served with yoghurt.", "8.50"),
        ("مشاوي جبران المشكلة", "Jubran Mixed Grill Platter", "كباب وشقف وشيش طاووق وريش مشوية على الفحم، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Chargrilled kebabs, shuqaf, shish tawouk and lamb chops, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "17.50"),
        ("كباب", "Kebab", "أسياخ لحمة مفرومة تقليدية، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Traditional minced meat skewers, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "13.00"),
        ("شقف", "Shuqaf", "أسياخ مكعبات فيليه لحمة متبلة ومشوية على الفحم، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Chargrilled meat fillet cube skewers with our special spices, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "17.50"),
        ("شيش طاووق", "Shish Tawouk", "أسياخ مكعبات دجاج متبلة ومشوية على الفحم، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Marinated chicken cube skewers, chargrilled, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "12.00"),
        ("ريش", "Lamb Chops", "ريش خروف متبلة ومشوية على الفحم، مع خضار مشوية وخبز أنطاكي وصلصة ثوم. يقدم على طبق ساخن.", "Chargrilled lamb chops in special spices, served with grilled vegetables, antakyali bread and garlic sauce. Served on a sizzling plate.", "17.00"),
    )),
    ("الحلويات", "Desserts", (
        ("بقلاوة بالبوظة", "Baklava Ice Cream", "بقلاوة مع بوظة. من توصيات الشيف.", "Baklava with ice cream. Chef's recommendation.", "10.50"),
        ("عثملية بالبوظة أو بالقشطة", "Othmaliya Ice Cream or Arabic Cream", "عثملية مع بوظة أو قشطة حسب اختيارك.", "Othmaliya with your choice of ice cream or Arabic cream.", "9.00"),
        ("كنافة", "Kunafa", "كنافة ساخنة. ممكن إضافة بوظة.", "Warm kunafa. Ice cream can be added.", "6.95"),
        ("فخارة أم علي", "Umm Ali Pot", "أم علي بالفخارة. يحتاج وقت تحضير أطول.", "Umm Ali baked in a clay pot. Needs extra preparation time.", "6.95"),
        ("تيراميسو ميلك كيك", "Tiramisu Milk Cake", "ميلك كيك بنكهة التيراميسو. من توصيات الشيف.", "Tiramisu-flavoured milk cake. Chef's recommendation.", "10.60"),
        ("هامينج بيرد كيك", "Hummingbird Cake", "كيك الهامينج بيرد. من توصيات الشيف.", "Hummingbird cake. Chef's recommendation.", "9.65"),
        ("شوكولاتة سوفليه", "Chocolate Soufflé", "سوفليه شوكولاتة ساخن. يحتاج وقت تحضير أطول.", "Warm chocolate soufflé. Needs extra preparation time.", "8.00"),
        ("تشيز كيك", "Cheesecake", "تشيز كيك، اسأل عن النكهات المتوفرة.", "Cheesecake; ask about today's flavours.", "8.00"),
    )),
    ("البوظة", "Ice Cream", (
        ("بوظة فستق حلبي", "Pistachio Ice Cream", "بوظة بالفستق الحلبي.", "Pistachio ice cream.", "5.75"),
        ("بوظة عربية", "Arabia Ice Cream", "بوظة عربية.", "Arabic ice cream.", "4.90"),
        ("بوظة سولتد كراميل", "Salted Caramel Ice Cream", "بوظة كراميل مملح.", "Salted caramel ice cream.", "4.90"),
        ("بوظة لوتس", "Lotus Ice Cream", "بوظة لوتس.", "Lotus ice cream.", "4.90"),
        ("بوظة أوريو", "Oreo Ice Cream", "بوظة أوريو.", "Oreo ice cream.", "4.90"),
        ("بوظة سنيكرز", "Snickers Ice Cream", "بوظة سنيكرز.", "Snickers ice cream.", "4.90"),
        ("بوظة شوكولاتة داكنة", "Dark Chocolate Ice Cream", "بوظة شوكولاتة داكنة.", "Dark chocolate ice cream.", "4.90"),
        ("بوظة شوكولاتة", "Chocolate Ice Cream", "بوظة شوكولاتة.", "Chocolate ice cream.", "4.65"),
        ("بوظة ڤانيلا", "Vanilla Ice Cream", "بوظة ڤانيلا.", "Vanilla ice cream.", "4.65"),
        ("بوظة فراولة", "Strawberry Ice Cream", "بوظة فراولة.", "Strawberry ice cream.", "4.65"),
    )),
    ("القهوة والشاي", "Coffee & Tea", (
        ("إسبريسو", "Espresso", "إسبريسو. متوفر بدون كافيين.", "Espresso. Decaf available.", "3.60"),
        ("قهوة تركية", "Turkish Coffee", "قهوة تركية. متوفرة بدون كافيين.", "Turkish coffee. Decaf available.", "3.60"),
        ("قهوة مفلترة", "Drip Coffee", "قهوة مفلترة.", "Drip coffee.", "4.35"),
        ("أمريكانو", "Americano", "أمريكانو.", "Americano.", "4.35"),
        ("قهوة بيضاء بماء الزهر", "White Rose Coffee", "قهوة بيضاء بماء الزهر.", "White coffee with orange blossom water.", "3.60"),
        ("أفوچاتو", "Affogato", "إسبريسو على بوظة ڤانيلا.", "Espresso poured over vanilla ice cream.", "6.85"),
        ("شاي", "Tea Selection", "خيارك من الشاي.", "Your choice of tea.", "3.75"),
        ("أعشاب طبيعية طازجة", "Fresh Herbal Selection", "خيارك من الأعشاب الطبيعية الطازجة.", "Your choice of fresh herbal infusion.", "3.75"),
        ("كرك", "Karak Chai", "شاي كرك بالحليب والهيل.", "Karak chai with milk and cardamom.", "5.45"),
        ("دلة قهوة عربية أو سعودية", "Coffee Pot (Arabian or Saudi)", "دلة قهوة عربية أو سعودية حسب اختيارك، تقدم مع تمر.", "A pot of Arabian or Saudi coffee (your choice), served with dates.", "13.00"),
    )),
    ("المشروبات الساخنة", "Hot Drinks", (
        ("لاتيه", "Caffè Latte", "لاتيه، ومتوفر إسباني أو بالفستق الحلبي.", "Caffè latte; also Spanish or pistachio.", "4.95"),
        ("لاتيه عسل وقرفة", "Cinnamon Honey Latte", "لاتيه بالعسل والقرفة.", "Latte with honey and cinnamon.", "4.95"),
        ("لاتيه سينامون لوتس", "Cinnamon Lotus Latte", "لاتيه بالقرفة واللوتس.", "Latte with cinnamon and lotus.", "5.65"),
        ("ماتشا لاتيه", "Matcha Latte", "ماتشا لاتيه بالعسل أو الكراميل أو الڤانيلا حسب اختيارك.", "Matcha latte with your choice of honey, caramel or vanilla.", "5.80"),
        ("كابتشينو", "Cappuccino", "كابتشينو.", "Cappuccino.", "4.60"),
        ("موكاتشينو", "Mochaccino", "موكاتشينو بالشوكولاتة.", "Mochaccino.", "5.40"),
        ("ميكياتو", "Macchiato", "ميكياتو.", "Macchiato.", "5.00"),
        ("كورتادو", "Cortado", "كورتادو.", "Cortado.", "5.95"),
        ("فلات وايت", "Flat White", "فلات وايت.", "Flat white.", "5.95"),
        ("شوكولاتة ساخنة", "Hot Chocolate", "شوكولاتة ساخنة.", "Hot chocolate.", "4.95"),
        ("قهوة فرنسية", "French Coffee", "قهوة فرنسية بالحليب.", "French coffee with milk.", "5.40"),
    )),
    ("القهوة المثلجة", "Iced Coffee", (
        ("قهوة مثلجة", "Iced Coffee", "قهوة مثلجة.", "Iced coffee.", "4.75"),
        ("لاتيه مثلج", "Iced Caffè Latte", "لاتيه مثلج.", "Iced caffè latte.", "4.85"),
        ("لاتيه فستق حلبي مثلج", "Iced Pistachio Latte", "لاتيه مثلج بالفستق الحلبي.", "Iced pistachio latte.", "5.40"),
        ("ماتشا لاتيه مثلج", "Iced Matcha Latte", "ماتشا لاتيه مثلج بالعسل أو الكراميل أو الڤانيلا حسب اختيارك.", "Iced matcha latte with your choice of honey, caramel or vanilla.", "5.80"),
        ("لاتيه إسباني مثلج", "Iced Spanish Latte", "لاتيه إسباني مثلج.", "Iced Spanish latte.", "5.95"),
        ("لاتيه كراميل مثلج", "Iced Caramel Latte", "لاتيه مثلج بالكراميل.", "Iced caramel latte.", "5.40"),
        ("لاتيه بندق مثلج", "Iced Hazelnut Latte", "لاتيه مثلج بالبندق.", "Iced hazelnut latte.", "4.95"),
        ("لاتيه ڤانيلا مثلج", "Iced Vanilla Latte", "لاتيه مثلج بالڤانيلا.", "Iced vanilla latte.", "4.95"),
    )),
    ("المشروبات الباردة", "Cold Drinks", (
        ("مياه معدنية", "Still Mineral Water", "مياه معدنية طبيعية.", "Still mineral water.", "2.25"),
        ("مياه غازية مستوردة", "Imported Sparkling Spring Water", "مياه ينابيع غازية مستوردة.", "Imported sparkling spring water.", "3.40"),
        ("صودا", "Soda", "صودا على اختيارك: كلاسيك، بتر ليمون، بنك ليمونيد أو جنجر إيل.", "Your choice of classic, bitter lemon, pink lemonade or ginger ale.", "3.60"),
        ("مشروبات غازية", "Soft Drinks", "مشروب غازي بارد.", "A cold soft drink.", "3.60"),
        ("مشروب طاقة", "Energy Drink", "مشروب طاقة.", "Energy drink.", "4.55"),
    )),
    ("العصائر الطازجة", "Fresh Juices", (
        ("عصير ليمون", "Lemon Juice", "عصير ليمون طازج.", "Fresh lemon juice.", "4.60"),
        ("ليمون بالنعنع", "Lemon with Mint", "عصير ليمون طازج بالنعنع.", "Fresh lemon juice with mint.", "4.95"),
        ("عصير برتقال", "Orange Juice", "عصير برتقال طازج.", "Fresh orange juice.", "4.70"),
        ("عصير كيوي", "Kiwi Juice", "عصير كيوي طازج.", "Fresh kiwi juice.", "5.00"),
        ("كيوي وليمون بالنعنع", "Kiwi Lemon Mint", "عصير كيوي وليمون بالنعنع.", "Fresh kiwi, lemon and mint juice.", "5.20"),
        ("عصير فراولة", "Strawberry Juice", "عصير فراولة طازج.", "Fresh strawberry juice.", "5.00"),
        ("عصير منجا", "Mango Juice", "عصير منجا طازج.", "Fresh mango juice.", "4.85"),
        ("عصير جوافة", "Guava Juice", "عصير جوافة طازج.", "Fresh guava juice.", "4.85"),
        ("عصير جزر", "Carrot Juice", "عصير جزر طازج.", "Fresh carrot juice.", "5.60"),
        ("عصير رمّان", "Pomegranate Juice", "عصير رمّان طازج.", "Fresh pomegranate juice.", "6.50"),
    )),
    ("الكوكتيلات الطازجة", "Fresh Mocktails", (
        ("أفوكادو فانتازي", "Avocado Fantasy", "أفوكادو وحليب وعسل وفستق حلبي.", "Avocado, milk, honey and pistachios.", "6.20"),
        ("سموذي توت مشكل", "Very Berry Smoothie", "توت أسود وتوت أزرق وتوت أحمر وفراولة.", "Blackberries, blueberries, raspberries and strawberries.", "8.00"),
        ("مانجو تروبيك", "Mango Tropic", "توت أحمر ومنجا وبرتقال.", "Raspberries, mango and orange.", "7.25"),
        ("تروبيكال تانجو", "Tropical Tango", "منجا وفراولة وكيوي وجوافة.", "Mango, strawberry, kiwi and guava.", "6.20"),
        ("غولدن سنست", "Golden Sunset", "برتقال وأناناس وخوخ وباشن فروت.", "Orange, pineapple, peach and passion fruit.", "6.20"),
        ("سانجريا (بدون كحول)", "Sangria (non-alcoholic)", "توت أسود وأزرق وأحمر وفراولة وشرائح برتقال وخوخ وعصير عنب. بدون كحول.", "Blackberries, blueberries, raspberries, strawberries, orange slices, peach and grape juice. Non-alcoholic.", "9.50"),
        ("شمندر وشوفان", "Beetroot Oats", "شمندر وشوفان وأناناس.", "Beetroot, oats and pineapple.", "6.65"),
    )),
    ("الموهيتو", "Virgin Mojito", (
        ("موهيتو توت مشكل", "Very Berry Mojito", "موهيتو بدون كحول بالتوت الأسود والأزرق والأحمر والفراولة.", "Virgin mojito with blackberries, blueberries, raspberries and strawberries.", "7.00"),
        ("موهيتو باشن فروت", "Passion Fruit Mojito", "موهيتو بدون كحول بالباشن فروت.", "Virgin passion fruit mojito.", "5.85"),
        ("موهيتو فراولة", "Strawberry Mojito", "موهيتو بدون كحول بالفراولة.", "Virgin strawberry mojito.", "5.75"),
        ("موهيتو كلاسيك", "Classic Mojito", "موهيتو بدون كحول بالليمون والنعنع.", "Classic virgin mojito with lime and mint.", "5.45"),
    )),
    ("الشاي المثلج", "Iced Tea", (
        ("آيس تي توت مشكل", "Very Berry Iced Tea", "شاي مثلج بالتوت الأسود والأزرق والأحمر والفراولة.", "Iced tea with blackberries, blueberries, raspberries and strawberries.", "5.70"),
        ("آيس تي خوخ", "Peach Iced Tea", "شاي مثلج بالخوخ.", "Peach iced tea.", "4.35"),
        ("آيس تي ليمون", "Lemon Iced Tea", "شاي مثلج بالليمون.", "Lemon iced tea.", "4.35"),
    )),
    ("الميلك شيك", "Milkshakes", (
        ("ميلك شيك فستق حلبي", "Pistachio Milkshake", "ميلك شيك بالفستق الحلبي.", "Pistachio milkshake.", "7.40"),
        ("ميلك شيك عربية", "Arabia Milkshake", "ميلك شيك بالبوظة العربية.", "Arabic ice cream milkshake.", "5.95"),
        ("ميلك شيك لوتس", "Lotus Milkshake", "ميلك شيك لوتس.", "Lotus milkshake.", "6.30"),
        ("ميلك شيك أوريو", "Oreo Milkshake", "ميلك شيك أوريو.", "Oreo milkshake.", "5.95"),
        ("ميلك شيك ڤانيلا", "Vanilla Milkshake", "ميلك شيك ڤانيلا.", "Vanilla milkshake.", "5.95"),
        ("ميلك شيك سولتد كراميل", "Salted Caramel Milkshake", "ميلك شيك بالكراميل المملح.", "Salted caramel milkshake.", "7.40"),
        ("ميلك شيك شوكولاتة", "Chocolate Milkshake", "ميلك شيك شوكولاتة.", "Chocolate milkshake.", "5.95"),
        ("ميلك شيك سنيكرز", "Snickers Milkshake", "ميلك شيك سنيكرز.", "Snickers milkshake.", "5.95"),
        ("ميلك شيك منجا باشن", "Mango Passion Milkshake", "ميلك شيك بالمنجا والباشن فروت.", "Mango and passion fruit milkshake.", "5.95"),
        ("ميلك شيك فراولة", "Strawberry Milkshake", "ميلك شيك فراولة.", "Strawberry milkshake.", "5.20"),
        ("ميلك شيك لوتس سينامون", "Cinnamon Lotus Milkshake", "ميلك شيك لوتس بالقرفة.", "Cinnamon lotus milkshake.", "6.30"),
        ("ميلك شيك بينا كولادا", "Piña Colada Milkshake", "ميلك شيك بينا كولادا (أناناس وجوز هند).", "Piña colada milkshake (pineapple and coconut).", "5.95"),
        ("ميلك شيك منجا بالريحان", "Mango Basil Milkshake", "ميلك شيك منجا بالريحان.", "Mango basil milkshake.", "5.95"),
        ("ميلك شيك جرجير وليمون", "Rocca Lemon Milkshake", "ميلك شيك بالجرجير والليمون.", "Rocca and lemon milkshake.", "5.20"),
    )),
    ("الأرجيلة", "Shisha", (
        ("أرجيلة تفاحتين", "Two Apples Shisha", "أرجيلة بنكهة التفاحتين.", "Two apples flavour shisha.", "8.00"),
        ("أرجيلة عنب", "Grapes Shisha", "أرجيلة بنكهة العنب.", "Grape flavour shisha.", "8.00"),
        ("أرجيلة عنب وتوت", "Grapes & Berries Shisha", "أرجيلة بنكهة العنب والتوت.", "Grape and berries flavour shisha.", "8.00"),
        ("أرجيلة عنب ونعنع", "Grape & Mint Shisha", "أرجيلة بنكهة العنب والنعنع.", "Grape and mint flavour shisha.", "8.00"),
        ("أرجيلة بلوميست", "Blue Mist Shisha", "أرجيلة بنكهة بلوميست.", "Blue mist flavour shisha.", "8.00"),
        ("أرجيلة مستكة", "Mastic Shisha", "أرجيلة بنكهة المستكة.", "Mastic flavour shisha.", "8.00"),
        ("أرجيلة ليمون ونعنع", "Lemon & Mint Shisha", "أرجيلة بنكهة الليمون والنعنع.", "Lemon and mint flavour shisha.", "8.00"),
        ("أرجيلة بطيخ ونعنع", "Watermelon & Mint Shisha", "أرجيلة بنكهة البطيخ والنعنع.", "Watermelon and mint flavour shisha.", "8.00"),
        ("أرجيلة علكة ونعنع", "Gum & Mint Shisha", "أرجيلة بنكهة العلكة والنعنع.", "Gum and mint flavour shisha.", "8.00"),
        ("أرجيلة علكة وقرفة", "Gum & Cinnamon Shisha", "أرجيلة بنكهة العلكة والقرفة.", "Gum and cinnamon flavour shisha.", "8.00"),
        ("أرجيلة لوڤ", "Love Shisha", "أرجيلة بنكهة لوڤ.", "Love flavour shisha.", "8.00"),
    )),
    ("أراجيل مميزة", "Premium Shisha", (
        ("أرجيلة كاندي", "Candy Shisha", "أرجيلة مميزة بنكهة كاندي.", "Premium candy flavour shisha.", "12.50"),
        ("أرجيلة نسمة شمام", "Melon Breeze Shisha", "أرجيلة مميزة بنكهة الشمام.", "Premium melon breeze shisha.", "15.00"),
        ("أرجيلة منجا منعشة", "Refreshing Mango Shisha", "أرجيلة مميزة بنكهة المنجا.", "Premium refreshing mango shisha.", "15.00"),
        ("أرجيلة جبران", "Jubran Shisha", "أرجيلة جبران المميزة بخلطة البيت.", "Jubran's premium house-blend shisha.", "16.00"),
        ("أرجيلة تفاحتين طازج", "Fresh Two Apples Shisha", "أرجيلة مميزة تفاحتين على رأس فاكهة طازجة.", "Premium two apples shisha on a fresh fruit head.", "16.00"),
        ("أرجيلة أناناس طازج بالشمام", "Fresh Pineapple & Melon Shisha", "أرجيلة مميزة أناناس وشمام على رأس فاكهة طازجة.", "Premium pineapple and melon shisha on a fresh fruit head.", "21.00"),
    )),
    ("إضافات الأرجيلة", "Shisha Add-ons", (
        ("أرجيلة صحية خاصة", "Disposable Shisha", "أرجيلة خاصة لمرة واحدة.", "A single-use personal shisha.", "4.00"),
        ("إضافة تفاحتين نخلة", "Two Apples Nakhla Add-on", "إضافة معسل تفاحتين نخلة.", "An extra head of Nakhla two apples.", "2.00"),
        ("بربيش صحي", "Healthy Hose", "بربيش صحي لمرة واحدة.", "A single-use hygienic hose.", "1.95"),
    )),
    ("الإضافات", "Extras", (
        ("إضافة دجاج", "Add Chicken", "دجاج إضافي على السلطة أو الشوربة أو الباستا أو الريزوتو أو الفريكة.", "Extra chicken on a salad, soup, pasta, risotto or freekeh.", "2.45"),
        ("إضافة لحم", "Add Meat", "لحمة إضافية على الحمص.", "Extra meat on hummus.", "1.50"),
        ("إضافة صنوبر", "Add Pine Nuts", "صنوبر إضافي على الحمص.", "Extra pine nuts on hummus.", "1.50"),
        ("إضافة زيت الكمأة", "Add Truffle Oil", "زيت الكمأة على أطباق الفرن والبيتزا.", "Truffle oil on oven dishes and pizzas.", "2.00"),
        ("إضافة بوظة", "Add Ice Cream", "بوظة إضافية مع الكنافة.", "Extra ice cream with kunafa.", "2.00"),
        ("إضافة فستق", "Add Pistachios", "فستق حلبي على كباب خشخاش.", "Pistachios on kebab khashkhash.", "0.80"),
    )),
)
